---
# defaults file for docker.elk
MYHOSTS:                     "p1-cloud"

work_dest:                   "/home/ansible"

src_folder:                  "/var/lib/docker/volumes/kibana_nginx_conf/_data"
conf_dest_folder:            "/var/lib/docker/volumes/nginx_conf/_data"
