---
# tasks file for roles/packer_builder
- name: Ping test
  win_ping:
  delegate_to: main

- name: Git clone
  git:
    repo: "{{ git_repo_gh }}"
    dest: "{{ path_to_temp }}"

- name: Add grants to scripts and converting .sh
  shell: >
    chmod +x {{ path_to_scripts }}/gen_checksum.sh &&
    dos2unix {{ path_to_scripts }}/gen_checksum.sh

- name: Execute scripts
  shell: "{{ item }}"
  loop:
    - chmod +x "{{ path_to_scripts }}/gen_checksum.sh"
    - "{{ path_to_scripts }}/gen_checksum.sh"

- name: Generate objects for Packer scenario
  template:
    src: "{{ item }}"
    dest: "{{ local_folder }}/{{ item | basename }}"
    mode: "0777"
  loop: "{{ query('fileglob', '{{ src_folder }}/*.j2', wantlist=True) }}"

- name: Rename objects for Packer scenario
  command: mv "{{ item }}" "{{ item | regex_replace('.j2$', '') }}"
  loop: "{{ lookup('fileglob', '{{ local_folder }}/*.j2', wantlist=True) }}"

- name: MV and structuring templates objects
  shell: >
    mv "{{ path_to_temp }}/ks.cfg" {{ path_to_temp }}/http

- name: CP .hcl files to packer_vb_centos-9 dir
  copy:
    src: "{{ item }}"
    dest: "{{ path_to_temp }}/packer_vb_centos-9/{{ item | basename }}"
  loop: "{{ lookup('fileglob', '{{ path_to_temp }}/*.hcl', wantlist=True) }}"

- name: CP .hcl files to packer_vm_centos-9 dir
  copy:
    src: "{{ item }}"
    dest: "{{ path_to_temp }}/packer_vm_centos-9/{{ item | basename }}"
  loop: "{{ lookup('fileglob', '{{ path_to_temp }}/*.hcl', wantlist=True) }}"

- name: Converting ks.cfg
  shell: dos2unix "{{ local_folder }}/http/ks.cfg"

- name: Insert to scenario value iso-checksum
  script: "{{ path_to_scripts }}/insert_value_checksum.py"
  args:
    executable: "{{ local_py_interpreter }}"

- name: RM useless objects .hcl
  shell: rm -f {{ path_to_temp }}/*.hcl

- name: CP obects Packer scenario in dest
  become: true
  copy:
    src: "{{ local_folder }}"
    dest: "{{ path_to_scenario }}"
    force: true

- name: RM git templates
  shell: rm -rf $HOME/temp/*

- name: Start Packer scenario for Virtualbox on Windows
  win_shell: |
    Set-Location "{{ path_to_scenario }}\packer\packer_vb_centos-9"
    & packer build .
  delegate_to: main
  when: status_vitualbox is true

- name: Start Packer scenario for VMware on Windows
  win_shell: |
    Set-Location "{{ path_to_scenario }}\packer\packer_vm_centos-9"
    & packer build .
  delegate_to: main
  when: status_vmware is true

- name: Remove directory structure
  win_file:
    path: "{{ path_to_scenario }}"
    state: absent
  ignore_errors: true
  delegate_to: main
