---
# tasks file for deploy_sdk_linux
- name: Ping test
  ping:

- name: Generate vars in a file for their use in a Scenario
  script: gen_vers_distribs.py
  delegate_to: localhost
  args:
    executable: "{{ local_py_interpreter }}"

- name: Add and Insert Data vars in vars_distribs.yml for Scenario
  include_vars:
    file: "{{ dest_path }}"

- name: Set Docker Repo URL from Template
  set_fact:
    docker_repo_url: "{{ lookup('template', 'docker_repo_url.j2') | trim }}"
  delegate_to: localhost

- name: Set Docker GPG key URL from Template
  set_fact:
    docker_gpg_url: "{{ lookup('template', 'docker_gpg_url.j2') | trim }}"
  delegate_to: localhost

- name: Execute Install Py Modules
  pip:
    name: "{{ py_modules }}"
    state: latest

#####Block for Debian/Ubuntu#####
- block:
    - name: Execute Upgrade unix Packages 'Debian/Ubuntu'
      apt:
        name: upgrade
        state: latest

    - name: Install utils/unix-packages for 'Debian/Ubuntu'
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: true

    - name: Add Docker Repository
      apt_repository:
        repo: "deb [arch=amd64] {{ docker_repo_url }} stable main"
        state: present
        update_cache: true

    - name: Add Docker GPG key
      apt_key:
        url: "{{ docker_gpg_url }}"
        state: present

    - name: Install SDK services for 'Debian/Ubuntu'
      apt:
        name: "{{ services }}"
        state: latest
        update_cache: true
      register: services_results
  when: vm_os_fam == "Debian"
     or vm_os_fam == "Ubuntu"

#####Block for RedHat#####
- block:
    - name: Execute Update unix Packages 'RedHat'
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Install utils/unix-packages for 'RedHat'
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: true

    - name: Add a Docker Repository
      yum_repository:
        name: docker-ce-stable
        description: Docker CE Stable
        baseurl: "{{ docker_repo_url }}"
        gpgcheck: true
        enabled: true
        gpgkey: "{{ docker_gpg_url }}"

    - name: Install SDK services for 'RedHat'
      yum:
        name: "{{ services + ['yum-utils'] }}"
        state: latest
        update_cache: true
      register: services_results
  when: vm_os_fam == "RedHat"

- name: Execute cmd updatedb
  shell: updatedb

- name: Check if docker-ce was Installed or Updated
  set_fact:
    docker_installed_or_updated: "{{ services_results.changes.installed | select('search', 'docker-ce') | list | length > 0 }}"

- name: Add ansible user to Docker group
  user:
    name: "{{ docker_user }}"
    password: "{{ docker_pw }}"
    generate_ssh_key: true
    ssh_key_type: ed25519
    ssh_key_file: .ssh/id_ed25519
    groups: docker

#####Block for Docker cmd#####
- block:
    - name: Start and Enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop: "{{ services_results.changes.installed | reject('search', 'docker-ce') + (docker_installed_or_updated | ternary(['docker'], [])) }}"

    - name: Check the Status in the Docker Containers
      shell: docker ps -q
      register: containers_status
      when: docker_installed_or_updated is true

    - name: Stop the Up Docker Containers
      shell: docker stop "{{ item }}"
      loop: "{{ containers_status.stdout_line }}"
      when: containers_status is not skipped and containers_status.stdout_lines | length > 0

    - name: Reboot services when Changed in Update
      service:
        name: "{{ item }}"
        state: restarted
      loop: "{{ services_results.changes.updated | reject('search', 'docker-ce') + (docker_installed_or_updated | ternary(['docker'], [])) }}"

    - name: Start Docker Containers
      shell: sleep 10 && docker start {{ item }}
      loop: "{{ containers_status.stdout_lines }}"
      when: containers_status is not skipped and containers_status.stdout_lines | length > 0
  become: false
  become_user: "{{ docker_user }}"

- name: Set Global Configurations for Git
  git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop: "{{ git_cfg }}"
  no_log: true

- name: Read SSH key from file on the remote host
  slurp:
    src: "{{ path_key }}"
  register: ssh_key_content

- name: Decode SSH key Content
  set_fact:
    ssh_key: "{{ ssh_key_content['content'] | b64decode }}"

- name: Remove User Posfix from SSH Key
  set_fact:
    clean_ssh_key: "{{ ssh_key.split(' ', 1)[0] + ' ' + ssh_key.split(' ', 2)[1] }}"

- name: Check SSH Key to GitHub
  uri:
    url: "{{ github_url }}"
    method: GET
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
  register: deployed_keys

- name: Check if the Key is already in use
  set_fact:
    key_exists: false

- name: Check each Key in the list
  set_fact:
    key_exists: true
  loop: "{{ deployed_keys.json }}"
  when: clean_ssh_key in item.key
  no_log: true

- name: Add SSH Key to GitHub
  uri:
    url: "{{ github_url }}"
    method: POST
    body_format: json
    headers:
      Authorization: "token {{ github_token }}"
    body:
      title: "{{ title_key }}"
      key: "{{ ssh_key }}"
    status_code: 201
  when: not key_exists
