---

- name: Create necessary volume vaultwarden_data for Vaultwarden
  ansible.builtin.docker_volume:
    name: vaultwarden_data
    state: present
  register: vaultwarden_data

- name: Create necessary volume vaultwarden_logs for Vaultwarden
  ansible.builtin.docker_volume:
    name: vaultwarden_logs
    state: present
  register: vaultwarden_logs

- name: Create/map necessary volume nginx_ssl for Vaultwarden
  ansible.builtin.docker_volume:
    name: nginx_ssl
    state: present
  register: nginx_ssl

- name: Create/map necessary volume nginx_conf for Vaultwarden
  ansible.builtin.docker_volume:
    name: nginx_conf
    state: present
  register: nginx_conf

- name: Create/map necessary volume nginx_stream for Vaultwarden
  ansible.builtin.docker_volume:
    name: nginx_stream
    state: present
  register: nginx_stream

- name: Ensure network exists
  ansible.builtin.docker_network:
    name: vaultwarden
    state: present

- name: Run Alt Vaultwarden container
  ansible.builtin.docker_container:
    name: vaultwarden
    image: fisher772/vaultwarden
    state: started
    restart_policy: unless-stopped
    hostname: vaultwarden
    volumes:
      - vaultwarden_data:/data/
      - vaultwarden_logs:/var/log/vaultwarden
      - nginx_ssl:/data/nginx
      - nginx_conf:/data/nginx/conf
      - nginx_stream:/data/nginx/stream
    env:
      TZ: "{{ EKB }}"
      LOG_FILE: "{{ ALT_LOGS }}"
      LE_FQDN: "{{ FQDN }}"
      CONTAINER_ALIAS: "{{ C_ALIAS }}"
      SERVER_ALIAS: "{{ S_ALIAS }}"
    networks:
      - name: nginx
      - name: vaultwarden
