---
# tasks file for docker.vaultwarden
- name: Ping test
  ping:

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Check Vaultwarden
  shell: docker ps -a | grep -q "vaultwarden"
  register: check_result
  ignore_errors: true

- block:
    - name: Stop container
      ansible.builtin.docker_container:
        name: vaultwarden
        state: stopped

    - name: Delete container
      ansible.builtin.docker_container:
        name: vaultwarden
        state: absent

    - name: Clear all unused Docker volumes
      ansible.builtin.docker_volume:
        prune: true

    - name: Delete image
      ansible.builtin.docker_image:
        name: vaultwarden/server
        state: absent
  when: check_result == 0

- import_tasks: "{{ import_file }}"
  when: import_status is true

- block:
    - name: Clone Git Repo
      git:
        repo: git@github.com:fisher772/docker_images.git
        dest: /tmp/git_remote_repo
        force: true

    - name: MV Conf files for Vaultwarden
      shell: mv "{{ src_folder }}/"*.conf "{{ conf_dest_folder }}"

    - name: MV Conf-stream files for Vaultwarden
      shell: mv "{{ src_folder }}/stream/"* "{{ stream_dest_folder }}"

    - name: Create necessary volume vaultwarden_data for Vaultwarden
      ansible.builtin.docker_volume:
        name: vaultwarden_data
        state: present
      register: vaultwarden_data

    - name: Run Vaultwarden container
      ansible.builtin.docker_container:
        name: vaultwarden
        image: vaultwarden/server
        state: started
        restart_policy: unless-stopped
        hostname: vaultwarden
        volumes:
          - vaultwarden_data:/data/
          - vaultwarden_logs:/var/log/vaultwarden
        env:
          TZ: "{{ EKB }}"
          LOG_FILE: "{{ LOGS }}"
        networks:
          - name: nginx

    - name: RM Git Repo
      file:
        name: /tmp/git_remote_repo
        state: absent
  when: import_status is not true
