centos_vers: [7, 8, 9]
rhel_vers: [7, 8, 9]
fedora_vers: [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40]
debian_vers: ['bookworm', 'bullseye', 'buster', 'jessie', 'stretch', 'wheezy']
ubuntu_vers: ['artful', 'bionic', 'cosmic', 'disco', 'eoan', 'focal', 'groovy', 'hirsute', 'impish', 'jammy', 'kinetic', 'lunar', 'mantic', 'noble', 'trusty', 'xenial', 'yakkety', 'zesty']
