---
- name: Test Connection to Test server and Select Facts VM
  hosts: test
  become: true

  tasks:
    - name: Ping test
      ping:

    - name: Store Facts of VM
      set_fact:
        vm_os_fam: "{{ ansible_facts['os_family'] }}"

- name: Install Py Modules
  hosts: test
  become: true
  gather_facts: false
  vars_files:
    - env.yml

  tasks:
    - name: Execute Install Py Modules
      pip:
        name: '{{ py_modules }}'
        state: latest
      register: results

    - name: Print result "Install Py Modules"
      debug:
        var: results
        verbosity: 4
      when: results is changed

- name: Install SDK
  hosts: test
  become: true
  gather_facts: false
  vars_files:
    - env.yml

  tasks:
#####Block for Debian/Ubuntu#####   
    - block:

        - name: Execute Update unix Packages 'Debian/Ubuntu'
          apt:
            name: upgrade
            state: latest

        - name: Install Repos for 'Debian/Ubuntu'
          apt:
            name: epel-release

        - name: Install utils/unix-apps for 'Debian/Ubuntu' 
          apt:
            name: '{{ packages }}'
            state: latest
          register: results

        - name: Print result "Install utils/unix-apps"
          debug:
            var: results
            verbosity: 4
          when: results is changed

      when: vm_os_fam == 'Debian' or
            vm_os_fam == 'Ubuntu'

#####Block for RedHat#####   
    - block:

        - name: Execute Update unix Packages 'RedHat'
          yum:
            name: '*'
            state: latest

        - name: Install Repos for 'RedHat'
          yum:
            name: epel-release

        - name: Install utils/unix-apps for 'RedHat' 
          yum:
            name: '{{ packages }}'
            state: latest
          register: results

        - name: Print result "Install utils/unix-apps"
          debug:
            var: results
            verbosity: 4
          when: results is changed

      when: vm_os_fam == 'RedHat'

- name: Start and Enable Services
  hosts: test
  become: true
  gather_facts: false

  tasks:
    - name: Check services Status and Daemon
      shell: systemctl status docker && systemctl is-enabled docker
      register: services_status
      ignore_errors: true

    - name: Execute cmd updatedb
      shell: updatedb

    - name: Start and Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes
      when: services_status.rc != 0

- name: Global Configuration of the Git config
  hosts: test
  become: true
  gather_facts: false
  vars_files:
    - env.yml
    - credentials.yml

  tasks:
    - name: Global Configuration for Git
      git_config:
        name: alias.ci
        scope: global

    - name: Read SSH key from file on the remote host
      slurp:
        src: "{{ path_key }}"
      register: ssh_key_content

    - name: Decode SSH key Content
      set_fact:
        ssh_key: "{{ ssh_key_content['content'] | b64decode }}"

    - name: Remove User Posfix from SSH Key
      set_fact:
        clean_ssh_key: "{{ ssh_key.split(' ', 1)[0] + ' ' + ssh_key.split(' ', 2)[1] }}"

    - name: Check SSH Key to GitHub
      uri:
        url: '{{ github_url }}'
        method: GET
        body_format: json
        headers:
          Authorization: "token {{ github_token }}"
      register: deployed_keys

    - name: Check if the Key is already in use
      set_fact:
        key_exists: false

    - name: Check each Key in the list
      set_fact:
        key_exists: true
      loop: '{{ deployed_keys.json }}'
      when: clean_ssh_key in item.key
      no_log: true

    - name: Add SSH Key to GitHub
      uri:
        url: '{{ github_url }}'
        method: POST
        body_format: json
        headers:
          Authorization: "token {{ github_token }}"
        body:
          title: '{{ title_key }}'
          key: '{{ ssh_key }}'
        status_code: 201
      when: not key_exists
      register: results
        
    - name: Print result "Add ssh Key to GitHub"
      debug:
        var: results
        verbosity: 4
      when: results is changed
