---
- name: Test Connection to Test server and Select Facts VM
  hosts: 
  - test
  - localhost
  become: true

  tasks:
    - name: Ping test
      ping:

    - name: Store Facts of VM1
      set_fact:
        vm_os_fam: "{{ ansible_facts['os_family'] }}"

    - debug:
        var: ansible_os_family

    - name: Store Facts of VM2
      set_fact:
        vm_os_release: "{{ ansible_facts['distribution_release'] }}"

    - debug:
        var: vm_os_release

  #  - debug:
  #      var: ansible_distribution_release

    - debug:
        var: ansible_distribution_major_version

    - debug:
        var: ansible_architecture
