---
# tasks file for local_dns
- name: Test ping
  ping:

#####Block for Debian/Ubuntu#####
- block:
    - name: Execute Update unix Packages 'Debian/Ubuntu'
      apt:
        name: upgrade
        state: latest

    - name: Install utils/unix-packages for 'Debian/Ubuntu'
      apt:
        name: "{{ packages + ['bind9utils'] }}"
        state: latest
        update_cache: true

    - name: Open port for DNS traffic on 'Debian/Ubuntu'
      ufw:
        rule: allow
        port: 161-162/udp

    - name: Install DNS services for 'Debian/Ubuntu'
      apt:
        name: "{{ services_other }}"
        state: latest
        update_cache: true
      register: services_results
      notify:
        - Started services if installed
        - Started services if updated
  when: vm_os_fam == "Debian"
     or vm_os_fam == "Ubuntu"

#####Block for RedHat#####
- block:
    - name: Execute Update unix Packages 'RedHat'
      yum:
        name: '*'
        state: latest
        update_cache: true

    - name: Install utils/unix-packages for 'RedHat'
      yum:
        name: "{{ packages + ['yum-utils'] + ['bind-utils'] }}"
        state: latest
        update_cache: true

    - name: Open port for DNS traffic on 'RedHat'
      ansible.posix.firewalld:
        port: 53/udp
        permanent: true
        state: enabled

    - name: Install DNS services for 'RedHat'
      yum:
        name: "{{ services_redhat }}"
        state: latest
        update_cache: true
      register: services_results
      notify:
        - Started services if installed
        - Restarted services if updated
  when: vm_os_fam == "RedHat"

#####Block for MV configs and Reboot DNS service#####
- block:
    - name: MV template config for DNS
      template:
        src: "named.conf.j2"
        dest: "/etc/named.conf"
        group: "{{ dns_user }}"
        mode: "0644"

    - name: MV template config for DNS-zone
      template:
        src: "bind.file.zone.j2"
        dest: "/var/named/{{ dns_zone_name }}.zone"
        group: "{{ dns_user }}"
        mode: "0644"
  notify:
    - Restart Bind
