---
# handlers file for vpn_l2tp
- name: Install packages for Speedtest
  community.general.snap:
    name:
      - fast
      - speedtest-cli

- name: Apply changes and Reload for sysctl
  shell: sysctl -p

- name: RM .sh Scritps
  file:
    path: /tmp/vpn_sh
    state: absent

#####Block for Debian/Ubuntu#####
- block:
    - name: Started Services if installed for 'Debian/Ubuntu'
      service:
        name: "{{ item }}"
        state: started
      loop:
        - strongswan-starter
        - xl2tpd
        - fail2ban
      when: services_results.changes.installed is defined

    - name: Restarted Services if updated for 'Debian/Ubuntu'
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - strongswan-starter
        - xl2tpd
        - fail2ban
      when: services_results.changes.updated is defined

    - name: Restarted Services for 'Debian/Ubuntu'
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - strongswan-starter
        - xl2tpd
        - fail2ban
  become: false
  become_user: "{{ vpn_user }}"
  when: vm_os_fam == "Debian"
     or vm_os_fam == "Ubuntu"

#####Block for RedHat#####
- block:
    - name: Started Services if installed for 'RedHat'
      service:
        name: "{{ item }}"
        state: started
      loop:
        - strongswan
        - xl2tpd
        - fail2ban
      when: services_results.changes.installed is defined

    - name: Restarted Services if updated for 'RedHat'
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - strongswan
        - xl2tpd
        - fail2ban
      when: services_results.changes.updated is defined

    - name: Restarted Services for 'RedHat'
      service:
        name: "{{ item }}"
        state: restarted
      loop:
        - strongswan
        - xl2tpd
        - fail2ban
  become: false
  become_user: "{{ vpn_user }}"
  when: vm_os_fam == "RedHat"
