---
# tasks file for docker.nginx
- name: Ping test
  ping:

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Check Nginx
  shell: docker ps -a | grep -q "nginx"
  register: check_result
  ignore_errors: true

- block:
    - name: Stop container
      ansible.builtin.docker_container:
        name: nginx
        state: stopped

    - name: Delete container
      ansible.builtin.docker_container:
        name: nginx
        state: absent

    - name: Clear all unused Docker volumes
      ansible.builtin.docker_volume:
        prune: true

    - name: Delete image
      ansible.builtin.docker_image:
        name: fisher/nginx-le
        state: absent
  when: check_result == 0

- name: Create necessary volume ssl for Nginx
  ansible.builtin.docker_volume:
    name: ssl
    state: present
  register: ssl

- name: Create necessary volume conf for Nginx
  ansible.builtin.docker_volume:
    name: conf
    state: present
  register: conf

- name: Create necessary volume nginx-logs for Nginx
  ansible.builtin.docker_volume:
    name: logs_nginx
    state: present
  register: logs_nginx

- name: Create necessary volume letsencrypt-logs for Nginx
  ansible.builtin.docker_volume:
    name: logs_letsencrypt
    state: present
  register: logs_letsencrypt

- name: Ensure network exists
  ansible.builtin.docker_network:
    name: nginx
    state: present

- name: Run Nginx container
  ansible.builtin.docker_container:
    name: nginx
    image: fisher772/nginx-le
    restart_policy: always
    hostname: nginx
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ ssl.volume.Mountpoint }}:/etc/nginx/ssl"
      - "{{ conf.volume.Mountpoint }}:/etc/nginx"
      - "{{ logs_nginx.volume.Mountpoint }}:/var/log/nginx"
      - "{{ logs_letsencrypt.volume.Mountpoint }}:/var/log/letsencrypt"
    env:
      TZ: "{{ EKB }}"
      LETSENCRYPT: "{{ STATUS }}"
      LE_EMAIL: "{{ EMAIL }}"
      LE_FQDN: "{{ FQDN }}"
      LE_CERT_CHAIN: "{{ CERT_CHAIN }}"
      LE_CERT_FQDN: "{{ CERT_FQDN }}"
      SERVER_ALIAS: "{{ ALIAS }}"
      VPN_ADDRESSES: "{{ SEC_IP }}"
      VPN_SEC: "{{ SEC_STATUS }}"
    networks:
      - name: nginx
