---
# tasks file for docker.nginx
- name: Ping test
  ping:

- name: Include path file vars
  include_vars:
    file: "{{ email_vars_path }}"
  when: vars_status is true

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Check Nginx
  shell: docker ps -a | grep -q "nginx"
  register: check_result
  ignore_errors: true

- block:
    - name: Stop container
      ansible.builtin.docker_container:
        name: nginx
        state: stopped

    - name: Delete container
      ansible.builtin.docker_container:
        name: nginx
        state: absent

    - name: Clear all unused Docker volumes
      ansible.builtin.docker_volume:
        prune: true

    - name: Delete image
      ansible.builtin.docker_image:
        name: fisher/nginx-le
        state: absent
  when: check_result == 0

- name: Create necessary volume ssl for Nginx
  ansible.builtin.docker_volume:
    name: ssl
    state: present
  register: ssl

- name: Create necessary volume conf for Nginx
  ansible.builtin.docker_volume:
    name: nginx_conf
    state: present
  register: nginx_conf

- name: Create necessary volume nginx-logs for Nginx
  ansible.builtin.docker_volume:
    name: nginx_logs
    state: present
  register: nginx_logs

- name: Create necessary volume letsencrypt-logs for Nginx
  ansible.builtin.docker_volume:
    name: letsencrypt_logs
    state: present
  register: letsencrypt_logs

- name: Ensure network exists
  ansible.builtin.docker_network:
    name: nginx
    state: present

- name: Run Nginx container
  ansible.builtin.docker_container:
    name: nginx
    image: fisher772/nginx-le
    restart_policy: always
    hostname: nginx
    published_ports:
      - "80:80"
      - "443:443"
    volumes:
      - ssl:/etc/nginx/ssl
      - nginx_conf:/etc/nginx
      - nginx_logs:/var/log/nginx
      - letsencrypt_logs:/var/log/letsencrypt
    env:
      TZ: "{{ EKB }}"
      LETSENCRYPT: "{{ STATUS }}"
      LE_EMAIL: "{{ EMAIL }}"
      LE_FQDN: "{{ FQDN }}"
      LE_CERT_CHAIN: "{{ CERT_CHAIN }}"
      LE_CERT_FQDN: "{{ CERT_FQDN }}"
      SERVER_ALIAS: "{{ ALIAS }}"
      VPN_ADDRESSES: "{{ SEC_IP }}"
      VPN_SEC: "{{ SEC_STATUS }}"
    networks:
      - name: nginx
