---
# handlers file for deploy_sdk_linux
- block:
    - name: Stop the Up Docker Containers
      shell: docker stop "{{ item }}"
      loop: "{{ containers_status.stdout_line }}"
      when: containers_status is not skipped and containers_status.stdout_lines | length > 0

    - name: Start and Enable services
      service:
        name: docker
        state: restarted
        enabled: true
      when: docker_installed_or_updated is true

    - name: Start Docker Containers
      shell: sleep 10 && docker start {{ item }}
      loop: "{{ containers_status.stdout_lines }}"
      when: containers_status is not skipped and containers_status.stdout_lines | length > 0
  become: false
  become_user: "{{ docker_user }}"

- name: Add a Docker mirrors
  copy:
    src: daemon.json
    dest: /etc/docker
  when: docker_mirrors_status is true
