---
# defaults file for deploy_sdk_linux
MYHOSTS:    'test'
dest_path:  '/home/ansible/ansible/projects/IAC/playbooks/roles/deploy_sdk_linux/vars/vers_distribs.yml'
github_url: 'https://api.github.com/user/keys'
path_key:   '/root/.ssh/id_ed25519.pub'
title_key:  'TEST'
local_py_interpreter: '/home/ansible/ansible/ansible-lint-venv/bin/python3'

vm_os_fam:     "{{ ansible_facts['os_family'] }}"
vm_os_distrib: "{{ ansible_facts['distribution'] }}"
vm_os_mj_ver:  "{{ ansible_facts['distribution_major_version'] }}"
vm_os_arch:    "{{ ansible_facts['architecture'] }}"
vm_os_release: "{{ ansible_facts['distribution_release'] }}"

url_docker_repo_centos: https://download.docker.com/linux/centos
url_docker_repo_rhel:   https://download.docker.com/linux/rhel
url_docker_repo_fedora: https://download.docker.com/linux/fedora
url_docker_repo_ubuntu: https://download.docker.com/linux/ubuntu/dists/
url_docker_repo_debian: https://download.docker.com/linux/debian/dists/

url_docker_gpg_centos:  https://download.docker.com/linux/centos/gpg
url_docker_gpg_rhel:    https://download.docker.com/linux/rhel/gpg
url_docker_gpg_fedora:  https://download.docker.com/linux/fedora/gpg
url_docker_gpg_ubuntu:  https://download.docker.com/linux/ubuntu/gpg
url_docker_gpg_debian:  https://download.docker.com/linux/debian/gpg
