---
# defaults file for deploy_sdk_linux
github_url: 'https://api.github.com/user/keys'
path_key:   '/root/.ssh/id_ed25519.pub'
title_key:  'TEST'

# vars for sdk
packages:
  - epel-release
  - mc
  - lsof
  - htop
  - vim
  - python3
  - curl
  - wget
  - telnet
  - docker
  - docker-compose
  - mlocate

py_modules:
  - packaging
  - setuptools
  - virtualenv
  - docker