---
# tasks file for docker.jenkins
- name: Ping test
  ping:

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Check Jenkins
  shell: docker ps -a | grep -q "jenkins"
  register: check_result
  ignore_errors: true

- block:
    - name: Stop container
      ansible.builtin.docker_container:
        name: jenkins
        state: stopped

    - name: Delete container
      ansible.builtin.docker_container:
        name: jenkins
        state: absent

    - name: Clear all unused Docker volumes
      ansible.builtin.docker_volume:
        prune: true

    - name: Delete image
      ansible.builtin.docker_image:
        name: fisher772/jenkins
        state: absent
  when: check_result == 0

- name: Create necessary volume adguard_work for Jenkins
  ansible.builtin.docker_volume:
    name: adguard_work
    state: present
  register: adguard_work

- name: Create necessary volume adguard_conf for Jenkins
  ansible.builtin.docker_volume:
    name: adguard_conf
    state: present
  register: adguard_conf

- name: Create/map necessary volume nginx_ssl for Jenkins
  ansible.builtin.docker_volume:
    name: nginx_ssl
    state: present
  register: nginx_ssl

- name: Create/map necessary volume nginx_conf for Jenkins
  ansible.builtin.docker_volume:
    name: nginx_conf
    state: present
  register: nginx_conf

- name: Create/map necessary volume nginx_stream for Jenkins
  ansible.builtin.docker_volume:
    name: nginx_stream
    state: present
  register: nginx_stream

- name: Ensure network exists
  ansible.builtin.docker_network:
    name: jenkins
    state: present

- name: Run Jenkins container
  ansible.builtin.docker_container:
    name: jenkins
    image: fisher772/jenkins
    restart_policy: unless-stopped
    hostname: jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
      - nginx_ssl:/data/nginx
      - nginx_conf:/data/nginx/conf
      - nginx_stream:/data/nginx/stream
    env:
      TZ: "{{ EKB }}"
      LE_FQDN: "{{ FQDN }}"
      CONTAINER_ALIAS: "{{ C_ALIAS }}"
      SERVER_ALIAS: "{{ S_ALIAS }}"
    networks:
      - name: nginx
      - name: jenkins
