---
# defaults file for docker.vaultwarden
MYHOSTS:                     "p1-cloud"

src_folder:                  "/tmp/git_remote_repo/vaultwarden/settings"
conf_dest_folder:            "/var/lib/docker/volumes/conf_nginx/_data/conf.d-le"
stream_dest_folder:          "/var/lib/docker/volumes/conf_nginx/_data/stream.d-le"
