---
# tasks file for docker.squid
- name: Ping test
  ping:

- name: Start Docker service
  service:
    name: docker
    state: started

- name: Check Squid
  shell: docker ps -a | grep -q "squid"
  register: check_result
  ignore_errors: true

- block:
    - name: Stop container
      ansible.builtin.docker_container:
        name: squid
        state: stopped

    - name: Delete container
      ansible.builtin.docker_container:
        name: squid
        state: absent

    - name: Clear all unused Docker volumes
      ansible.builtin.docker_volume:
        prune: true

    - name: Delete image
      ansible.builtin.docker_image:
        name: fisher772/squid
        state: absent
  when: check_result == 0

- name: Create necessary volume cache for Squid
  ansible.builtin.docker_volume:
    name: squid_cache
    state: present
  register: squid_cache

- name: Create necessary volume logs for Squid
  ansible.builtin.docker_volume:
    name: squid_logs
    state: present
  register: squid_logs

- name: Create necessary volume data for Squid
  ansible.builtin.docker_volume:
    name: squid_data
    state: present
  register: squid_data

- name: Ensure network exists
  ansible.builtin.docker_network:
    name: squid
    state: present

- name: Run Squid container
  ansible.builtin.docker_container:
    name: squid
    image: fisher772/squid
    restart_policy: always
    hostname: squid
    published_ports:
      - "8888:8888"
    volumes:
      - squid_cache:/var/spool/squid
      - squid_logs:/var/log
      - squid_data:/etc/squid
    env:
      TZ: "{{ EKB }}"
      HTTP_PORT: "{{PORT}}"
      DNS_VALUE: "{{DNS}}"
      #TRUSTED_IP: "{{ T_IP }}"
    networks:
      - name: nginx
      - name: squid
